name: Assign Issue to Project

on:
  workflow_dispatch:  # This line allows manual triggering of the workflow
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - develop

jobs:
  add-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Issue
      run: |
        echo "Adding issue to repository..."
