name: Assign Issue to Project

on:
  workflow_dispatch:  # This line allows manual triggering of the workflow
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - develop

jobs:
  assign-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to organization project
        uses: skeet70/default-project-board-action@v1
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          issue: ${{ github.event.issue.number }}
          project: 1
