name: Reminder Inactive PRs

on:
  workflow_dispatch:  # This line allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - develop
  push:
    branches:
      - develop

permissions:
  issues: write
  pull-requests: write

jobs:
  remind-inactive-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Reminder for Inactive PRs
        uses: lee-dohm/issue-reminder@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-reminder: 4
          reminder-label: 'inactive'
          only-issue-creators: false # Set to true if you only want to notify issue creators
          only-assigned-issues: false # Set to true if you only want to notify assigned issues
          ignore-issues-with: 'wontfix, duplicate' # Add labels to ignore
